name: pyrolite-meltsutil

channels:
  - conda-forge # get things from conda-forge first
  - defaults

dependencies:
  - python=3.7
  # pandas and scientific python
  - numpy
  - numpydoc
  - pandas>=1.0  # dataframe acccessors, attrs attribute
  - xlrd
  - openpyxl
  - psutil
  - matplotlib # note that 3.4+ is incompatible with mpltern <0.3.3
  - pytables
  - scipy>=1.2  # uses scipy.optimize.Bounds, added around 1.2
  - umap-learn
  - tinydb
  - periodictable
  - mpltern>=0.3.1
  - mpmath
  - sympy
  - joblib
  - requests
  # Tools
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
  - black
  - jedi<0.18.0 # for use on atom/ipython
  - pip:
    - pyzmq
    - pytest
    - pytest-runner
    - pytest-cov
    - coverage
    - codecov
    - sphinx_rtd_theme
    - sphinx-autodoc-annotation
    - sphinx_gallery>=0.6.0
    - recommonmark
    - versioneer
    - twine
    - pyrolite
    - -e . # install the local pyrolite-meltsutil package

# conda env create -f environment.yml
# python -m ipykernel install --user --name pyrolite-meltsutil

# conda activate pyrolite-meltsutil

# conda deactivate pyrolite-meltsutil
# conda env remove -n pyrolite-meltsutil
# jupyter kernelspec uninstall pyrolite-meltsutil

# make sure to launch Jupyter, atom etc from the command line after activating
