name: pyrolite-meltsutil

channels:
  - conda-forge # get things from conda-forge first
  - defaults

dependencies:
  - python=3.10
  # pandas and scientific python
  - pyrolite
  - numpy
  - numpydoc
  - pandas>=1.0 # dataframe acccessors, attrs attribute
  - xlrd
  - openpyxl
  - psutil
  - matplotlib # note that 3.4+ is incompatible with mpltern <0.3.3
  - pytables
  - scipy>=1.2 # uses scipy.optimize.Bounds, added around 1.2
  - umap-learn
  - tinydb
  - periodictable
  - mpltern>=0.4.0
  - mpmath
  - sympy>=1.7 # import changes after sympy 1.6
  - joblib
  - requests
  # Tools
  - jupyter
  - jupyterlab
  - jupyterlab-spellchecker
  - jupyterlab_code_formatter
  - ipykernel
  - pip
  - black
  - isort
  - pyzmq
  - pytest
  - pytest-runner
  - pytest-cov
  - coverage
  - codecov
  - sphinx_rtd_theme
  - recommonmark
  - versioneer
  - twine
  - pip:
      - sphinx-autodoc-annotation
      - sphinx_gallery>=0.6.0
      - -e . # install the local pyrolite-meltsutil package

# conda env create -f environment.yml
# python -m ipykernel install --user --name pyrolite-meltsutil

# conda activate pyrolite-meltsutil

# conda deactivate pyrolite-meltsutil
# conda env remove -n pyrolite-meltsutil
# jupyter kernelspec uninstall pyrolite-meltsutil

# make sure to launch Jupyter, atom etc from the command line after activating
