name: pyrolitemeltsutildocs

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - matplotlib
  - scipy>=1.2
  - pandas>=0.23
  - pip:
      - -e git+git://github.com/morganjwilliams/pyrolite-meltsutil.git@develop#egg=pyrolite-meltsutil[dev]
