name: DocsTest

on:
  push:
  pull_request:
    branches:
      - develop
      - feature/**
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  build:
    name: Build Docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "setup.py"
      - name: Python Packages Install
        run: |
          python -m pip install --upgrade pip  # upgrade pip
          pip install wheel
          pip install .[docs]
      - name: Build
        run: |
          cd docs && make html
