name: DocsTest

on:
  push:
  pull_request:
    branches:
    - develop
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    name: Build Docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Python Packages Install
        run: |
          python -m pip install --upgrade pip  # upgrade pip
          pip install wheel
          pip install .[docs]
      - name: Build
        run: |
          cd docs && make html
